export default [
  {
    logo: '/images/shops/1.jpg',
    name: 'Engine car',
    description: 'Лучший магазин автозапчастей',
    staff: 6,
    address: 'СПб Тест 23',
    phone: '+7 981 321 65 48',
  },
  {
    logo: '/images/shops/2.jpg',
    name: 'Аттестация',
    description: 'Лучший магазин автозапчастей',
    staff: 11,
    address: 'СПб Тест 34',
    phone: '+7 981 234 65 48',
  },
  {
    logo: '/images/shops/3.jpg',
    name: 'Motors shop',
    description: 'Лучший магазин автозапчастей',
    staff: 23,
    address: 'СПб Тест 23',
    phone: '+7 345 321 65 48',
  },
  {
    logo: '/images/shops/4.jpg',
    name: 'Company one',
    description: 'Лучший магазин автозапчастей',
    staff: 3,
    address: 'СПб Тест 26',
    phone: '+7 981 345 65 48',
  },
  {
    logo: '/images/shops/5.jpg',
    name: 'БИ-БИ',
    description: 'Лучший магазин автозапчастей',
    staff: 16,
    address: 'СПб Тест 34',
    phone: '+7 981 321 23 48',
  },
]
